
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

version: 1.0.{build}

branches:
  only:
    - master

os: Visual Studio 2015

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.7\msvc2015
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86'
  - ps : .\bitbucket.ps1
  - qmake rejif.pro
  - dir
  - nmake
  - dir

after_build:
  - ps : xcopy lib release/lib /Y
  - cd release
  - windeployqt --no-compiler-runtime --no-translations --release regif.exe
  - ps : rm *.cpp
  - ps : rm *.h
  - ps : rm *.obj
  - dir

artifacts:
  - path: release
    name: rejif
  - path: release/rejif.exe
    name: rejif.exe
